### ISSUE TITLE
Adds "." even though last character is "!" or already is "."

### ISSUE THREAD

**Issue by kristinekf** [dliso/crowbot#11]
Koden skal legge til et punktum hvis meldingen fra bot-en ikke har utropstegn eller punktum fra før av. Men den legger til punktum uansett på "greeting" og "fallback" uansett... får ikke til å fikse det. Vi bør også legge til kode sånn at det ikke blir lagt til punktum etter spørsmålstegn. 
Relevant fil: frontend/script.js

**Comment by mariefbj** [comment]
I fix soon! :)

**Comment by dliso** [comment]
Fixed in #12
