### ISSUE TITLE
Fylle database med spørsmål

### ISSUE THREAD

**Issue by mariefbj** [dliso/crowbot#36]
Lage en manage.py command som fyller Question modellen i databasen med spørsmål som ofte blir stilt typ. 
- "Hvor mange øvinger må godkjennes?"
- "Hvis jeg har godkjent øvingsopplegg fra før, må jeg likevel gjøre det dette året?"
- "Hvor mange øvinger er det i dette faget?"
- "Hvor mange øvinger må man gjøre for å kunne gå opp til eksamen?"
- "Hvilken lærebok brukes i dette faget? utgave?"
- "Når og hvor er første forelesning?"
- "Hva er hjemmesiden til faget?"

Legge dette inn for alle emner.

Kommando for å legge inn spørsmålene er nå: 
python manage.py fill_question_database

**Comment by dliso** [comment]
#47
