### ISSUE TITLE
"About" del til nettsiden

### ISSUE THREAD

**Issue by mariefbj** [dliso/crowbot#41]
Skal vi legge til en "About" del på nettsiden som forklarer hvordan programmet fungerer på innsiden, typ hvilke spørsmål som støttes av API.AI? Eller blir det for mye info og bør klassifiseres som bedriftshemmelighet? 😅

**Comment by mariefbj** [comment]
Heller at dette blir en slags "hjelpeside" som bruker kan klikke seg inn på ved førstegangs bruk elns

**Comment by dliso** [comment]
#59, #72

**Comment by dliso** [comment]
Modalen er der, nå må vi bare legge inn riktig tekst.

**Comment by dliso** [comment]
#83 la til teksten.
